steps:
  - read: name
    prompt: "Please enter a name for your app (e.g., my-asgardeo-react):"
    fallback: "asgardeo-react"

  - read: version
    prompt: "Please enter the version for your app (default: 0.1.0):"
    fallback: "0.1.0"

  - read: author
    prompt: "Please enter the app author's name:"
    fallback: "WSO2" 

  - read: clientId
    prompt: "Please enter your Asgardeo Client ID:"
    fallback: "<your-app-client-id>"

  - read: organization_name
    prompt: "Please enter your Asgardeo Organization name:"
    fallback: "<your-organization-name>"
  
  - update: package.json
  - update: src/main.jsx
  
  - remove: LICENSE
  - remove: README.md
  - remove: .github
  - remove: .tmplr.yml
